basePath: /api/v1
host: localhost:8080
info:
  contact: {}
  description: Notification Service
  title: Notify Service
  version: v1.0.0
paths:
  /messages/send:
    post:
      description: Отправляет сообщение пользователю с заданными полями
      responses:
        "200":
          description: success
        "500":
          description: Не удалось создать нотификацию
        "504":
          description: Время ожидания вышло
      summary: Отправка сообщения
      tags:
      - Notify
  /user/preferences:
    put:
      description: Изменяет предпочтения пользователя
      responses:
        "200":
          description: success
        "500":
          description: Не удалось изменить предпочтения
        "504":
          description: Время ожидания вышло
      summary: Изменение предпочтений
      tags:
      - Preferences
swagger: "2.0"
